# Generated by Django 5.2.13 on 2026-04-27 01:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='💻', help_text='Single emoji shown on the dashboard card.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_question', models.TextField(blank=True)),
                ('candidate_transcript', models.TextField(blank=True)),
                ('llm_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('vision_confidence_score', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='coach.teststream')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
